parserOptions:
  ecmaVersion: 10
  sourceType: module
  ecmaFeatures:
    jsx: true
env:
  es6: true
  node: true
extends:
  - prettier
  - eslint:recommended
  - plugin:react/recommended
plugins:
  - prettier
  - react
rules:
  prettier/prettier:
    - error
    - singleQuote: true